import React from 'react';
import styles from './landing-page.module.css'; // Import the CSS module
import Link from 'next/link'; // Import Link for navigation

export default function LandingPage() {
  return (
    <div className={styles.pageContainer}>
      {/* Navbar Section - REMOVED (Now handled globally) */}
      {/* 
      <nav className={styles.navbar}>
        <div className={styles.navbarBrand}>
          Zero AI
        </div>
        <div className={styles.navbarActions}>
          <Link href="/login" passHref>
            <button className={styles.loginButton}>Login</button>
          </Link>
        </div>
      </nav>
      */}

      <div className={styles.contentWrapper}>
        {/* Header Section - REMOVED */}
        {/* 
        <header className={styles.header}>
          <h1 className={styles.mainHeading}>
            Zero AI
          </h1>
          <p className={styles.subHeading}>
            Go from 0 to 0.5 in any unfamiliar field.
          </p>
        </header>
        */}

        {/* Vision Section */}
        <section className={styles.section}>
          <h2 className={styles.sectionHeading}>
            Our Vision
          </h2>
          <p className={styles.sectionParagraph}>
            At Zero AI, we believe that the beginning of every journey is the most important step.
            Our mission is to empower curious minds to explore new fields effortlessly, by breaking down barriers to knowledge and providing a personalized, gamified learning experience.
            We envision a future where learning is lightweight, joyful, and truly accessible for everyone starting from zero.
          </p>
        </section>

        {/* Product Description Section */}
        <section className={styles.section}>
          <h2 className={styles.sectionHeading}>
            How It Works
          </h2>
          <div className={styles.featureGrid}>
            {/* Feature Card 1 */}
            <div className={styles.featureCard}>
              <h3 className={styles.featureCardHeading}>
                Keyword Cards
              </h3>
              <p className={styles.featureCardText}>
                The smallest unit of knowledge, offering clear explanations, examples, and resources.
              </p>
            </div>
             {/* Feature Card 2 */}
            <div className={styles.featureCard}>
              <h3 className={styles.featureCardHeading}>
                Learning Paths
              </h3>
              <p className={styles.featureCardText}>
                Personalized routes built around your interests and goals, generated by AI Agents.
              </p>
            </div>
             {/* Feature Card 3 */}
            <div className={styles.featureCard}>
              <h3 className={styles.featureCardHeading}>
                Achievement System
              </h3>
              <p className={styles.featureCardText}>
                Visualize your progress, collect milestones, and build a structured knowledge map.
              </p>
            </div>
          </div>
          {/* Added productDescriptionClosingParagraph for specific margin */}
          <p className={`${styles.sectionParagraph} ${styles.productDescriptionClosingParagraph}`}>
            Whether you're switching careers, exploring a new hobby, or simply feeding your curiosity, Zero AI helps you take the first meaningful step — and keeps you motivated along the way.
          </p>
        </section>

        {/* Waitlist Section */}
        <section className={styles.waitlistSection}>
          <h2 className={styles.waitlistHeading}>
            Join the Waitlist
          </h2>
          <p className={styles.waitlistText}>
            Be among the first to experience the future of learning with Zero AI.
          </p>
          <button className={styles.waitlistButton}>
            🚀 Get Early Access
          </button>
        </section>

      </div>
    </div>
  );
}
